# Generated by Django 5.1.6 on 2025-03-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uptdated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
